### PR TITLE
chore: add funding field

### PR DESCRIPTION
**Pull request by amareshsm**
### Description:

Added funding field.

### CODE REVIEW

**Comment by nzakas** [comment]
I’m not sure if things were already broken, but this has breaking CI checks.

**Comment by bmish** [comment]
This PR fixes it: https://github.com/eslint/generator-eslint/pull/129

**Comment by amareshsm** [comment]
> This PR fixes it: #129

Yes, it is fixed. All checks were passed.

**Review by nzakas — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
