### PR TITLE
Chore: Replace deprecated `require-uncached` with `import-fresh`

### PR DESCRIPTION
**Pull request by bmish**
require-uncached renamed to import-fresh: https://github.com/sindresorhus/import-fresh/releases/tag/v3.0.0

https://www.npmjs.com/package/require-uncached

Part of #86.

### CODE REVIEW

**Comment by nzakas** [comment]
It might be easier to do all of these dependency updates in one PR to avoid conflicts.

**Comment by bmish** [comment]
Fixed conflict. The good news is that I'm just about done with dependency updates, except for the yeoman dependencies which I'll do together.

**Review by snitin315 — APPROVED** [review]
Looks Good, Thanks!

**Comment by aladdin-add** [comment]
conflicts need to be resolved here. @bmish

**Comment by bmish** [comment]
Fixed conflicts.

**Review by aladdin-add — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
