### PR TITLE
Fix: add mocha as a dependency (fixes #32)

### LINKED ISSUE #32: Shouldn't mocha be listed as a devDependency?
I wasn't able to get the tests to run until I installed mocha-cli globally and mocha locally.

```sh
npm install -g mocha-cli
npm install --save-dev mocha
```

Maybe I'm missing something, but shouldn't mocha be included as a dev dependency? And can we avoid depending on the presence of the mocha command by referencing `./node_modules/mocha/bin/mocha` directly?

### PR DESCRIPTION
**Pull request by pmcelhaney**
Adds mocha as a dependency in the package.json template.

### CODE REVIEW

**Comment by platinumazure** [comment]
Nice! Thanks for the PR!

Two questions, which hopefully @nzakas can help answer:

1. Should this be tested somehow? (Presumably not down to the specified version, just that the generated file contains devDependencies with mocha)
1. Does the jQuery CLA requirement apply here at this point, and if so, is the jQuery bot operating on this repository? And @pmcelhaney have you by any chance [signed the jQuery CLA](https://contribute.jquery.org/CLA/)?

**Comment by pmcelhaney** [comment]
1. I don't see anything that tests the contents of package.json now. It might make sense to check that package.json is valid. 

2. I've signed an SLA for ESLint before. I don't remember it having anything to do with jQuery but just in case I just signed that one.

**Comment by platinumazure** [comment]
Thanks @pmcelhaney. You are right that ESLint used to have its own CLA, but we've recently [joined the jQuery foundation](http://eslint.org/blog/2016/04/eslint-joins-the-jquery-foundation). Now they're taking care of ESLint on the legal side, so they want everyone to use their own CLA.

If you signed the jQuery Foundation CLA and this PR wasn't updated, unfortunately that means their bot account isn't configured for this repo yet and @nzakas will have to verify manually. Hopefully not a big deal in the grand scheme of things.

Thanks so much for your patience with the new legal stuff. Hopefully @nzakas will get a chance to review this soon-ish.

**Comment by nzakas** [comment]
Sorry, lost track of this. So yes, technically we need the jQuery CLA signed. The bot didn't show up here because the PR was created before the bot was setup. The CLA is here: http://contribute.jquery.org/CLA/

I don't think we need anything to test this change.

**Comment by platinumazure** [comment]
This PR looks good to me. Merging this in for now; however, I do note that both the mocha and ESLint versions are not current. Perhaps long-term we should see if we can use npm to get the current version at runtime.

**Pull request merged**
