### PR TITLE
Plugin Generator

### PR DESCRIPTION
**Pull request by nzakas**
Builds on #7.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Very nice! Should we include .md file generation? Also, should there be generator for separate rules for plugins?

**Comment by nzakas** [comment]
What would an .md file be for here?

The rule generator also supports plugins.

**Comment by ilyavolodin** [comment]
Well, I personally list all of the available rules in the .md file and installation instructions for the plugin. I think most of the plugins for ESLint copied my repository style, so a lot of them do. I don't think it's a must have, but might be nice to generate .md file with installation instructions at least.

**Comment by Nate-Wilkins** [comment]
:+1: To the .md file - I personally like @ilyavolodin's documentation for plugin rules and have used a very similar one in `eslint-plugin-bdd`

**Comment by nzakas** [comment]
It sounds like you're both talking about a README?

**Comment by ilyavolodin** [comment]
Sorry, I wasn't clear, I meant something like this: https://github.com/ilyavolodin/eslint-plugin-backbone/blob/master/README.md general readme file for plugin's repository.
Now that you mention it though, we should also update README file for this repository to mention this template too.

**Comment by nzakas** [comment]
Oh yeah, good call.

**Comment by nzakas** [comment]
Updated the README and create an example README for plugins. Yay!

**Comment by ilyavolodin** [comment]
Nice! Looks good to me!

**Pull request merged**
