### PR TITLE
Added lint config prompt to generator

### PR DESCRIPTION
**Pull request by darkwebdev**
After creating all the files asks about how to configure eslint for the project itself.

### CODE REVIEW

**Comment by darkwebdev** [comment]
The only problem now is that generated code gives you linting errors depending on which rules you use.

**Comment by platinumazure** [comment]
I think I'd like this behavior to be opt-in. Can we add a prompt asking if the user wants to run `eslint --init`, and then use that prompt answer to decide if it should be run?

Also, would it make sense to add the `eslint --init` logic to one of the run loop named queues?

**Comment by darkwebdev** [comment]
Yeah, it would be cool to use composition here, but I'd suggest first to apply a feature and leave rafactoring for later (maybe I'm wrong thou).

**Comment by platinumazure** [comment]
Yeah, for sure, I was just rambling about long-term vision I guess. :smile:

Would you mind rebasing on master? I've added AppVeyor configuration so we can make sure that your PR will also work on a Windows CI.

**Comment by darkwebdev** [comment]
appveyor still fails...

**Comment by darkwebdev** [comment]
@platinumazure I've rebased, but appveyor tests fail, thou everything's green locally

**Comment by kaicataldo** [comment]
Closing this stale PR. Thanks for being willing to contribute to ESLint!

**Pull request closed without merging**
