### PR TITLE
Chore: Use require-uncached to avoid stale cache in tests (fixes #44)

### LINKED ISSUE #44: Caching problem in tests (same generator and/or same prompts are used in different tests)
~~Extracted from #42. That issue talks about us not escaping double quotes correctly when putting user input in JS code; this one talks about single quotes being replaced by double quotes somewhere in the generator internals.~~

Of course it's a caching problem.

### PR DESCRIPTION
**Pull request by platinumazure**
Adding single quote pathological tests as well (although those aren't actually pathological for us, I just wanted to have coverage for weird input).

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[x] Bug fix ([template](https://raw.githubusercontent.com/eslint/eslint/master/templates/bug-report.md))
[ ] Add something to the core
[x] Other, please explain: The "bugfix" isn't user-facing, it just got in the way of writing good generator tests.

See issue #44.

**What changes did you make? (Give an overview)**

Added require-uncached to devDependencies and used it in plugin/rule tests to avoid `require()` cache problems. Also improved tests and added some new tests.

**Is there anything you'd like reviewers to focus on?**

Should be pretty straightforward, let me know if you have questions.

### CODE REVIEW

**Comment by zxqfox** [comment]
RequireUncached package using `delete` for recursive cleaning real require cache.
https://github.com/hravnx/requireUncached/blob/master/index.js#L33

Much better way is to avoid it and just evaluate commonjs/json modules like node.js it does.
https://github.com/nodules/file-eval/ or https://github.com/nodules/node-eval/

Can be used like `requireUncached = path => require('node-eval')(fs.readFileSync(path), path);` for drop in replacement.

Here I see just `.json` files so it's overengineering to use require at all. It literally works like: `requireJson = path => JSON.parse(fs.readFileSync(path, 'utf-8'))` and no need in requiring and cache cleaning here.

**Comment by platinumazure** [comment]
@zxqfox Thanks for the suggestion! For what it's worth, no, there are JS files being required here, not just JSON. That's part of why I wanted to use `require`, for that convenience. Does `node-eval` work with JSON as well?

If there's a preference to use node-eval, I'm not opposed, I just wanted to make sure you had all the right information.

**Comment by zxqfox** [comment]
> Does node-eval work with JSON as well?

Yes it does if you pass filename. JSON can't be evaluated as JS so there is another if (ext=json) for that purpose. Literally it works just like require does. I'm just afraid about recursive requires because there are no tests for that.

> If there's a preference to use node-eval, I'm not opposed, I just wanted to make sure you had all the right information.

I'm thinking about coverage. Should we calculate coverage for files we requiring with requireUncached? In that way it could be little be harder. Not much tho.

**Comment by platinumazure** [comment]
Oh, I just noticed you're referring to RequireUncached. I'm using
sindresorhus/require-uncached, which as far as I can tell does not
recursively delete cache entries. I don't need recursive deletion so that's
okay.

**Comment by platinumazure** [comment]
@zxqfox Not sure I understand your question about coverage, could you please elaborate?

**Comment by zxqfox** [comment]
@platinumazure I thought we should calculate coverage for requiring with requireuncached files. I was wrong.

**Comment by platinumazure** [comment]
@zxqfox Awesome, thanks for clarifying. Did you have any outstanding concerns?

**Comment by zxqfox** [comment]
@platinumazure Everything else looks good to me.

**Comment by platinumazure** [comment]
Okay, I'm going to go ahead and merge this. I'm happy to deal with any other issues in a separate PR. Thanks!

**Pull request merged**
