### PR TITLE
Fix: fix rule id and plugin id validator (fixes #11)

### LINKED ISSUE #11: rule id regex does not accept numbers
this intentional? or should I fix?

### PR DESCRIPTION
**Pull request by meeech**
- pulled out the validators to their own file, and use the same regex for plugin id and rule id
- added tests

### CODE REVIEW

**Comment by ilyavolodin** [comment]
LGTM

**Comment by meeech** [comment]
@nzakas no problem. forgot to update test.

* i didn't add @author since to validators - i didn't write most of it - it was from what you had before, with the fixed up regex
* no copyright on the test file, because really, i don't want any. 

if there's any other problem please let me know the specifics, since i'm not seeing any others.

**Comment by nzakas** [comment]
@meeech those are the things you need to address. If you want to use my name instead of yours, that's fine, but we do need the information in there.

**Comment by meeech** [comment]
@nzakas done and done.

**Comment by nzakas** [comment]
Thanks!

**Pull request merged**
